# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

fibonacci = []

buffer = [1, 0]  # Circular buffer for holding previous 2 terms

FOUR_MILLION = 4 * (10 ** 6)

i = 1
while True:
    value = buffer[0] + buffer[1]

    if value > FOUR_MILLION:
        break

    if value % 2 == 0:
        fibonacci.append(value)

    buffer[i % 2] = value
    i += 1

print 'ready'
print sum(fibonacci)
